### ISSUE TITLE
AnimationComponent functionality

### ISSUE THREAD

**Issue by AlmasB** [marvinbuff/GalacticCombat#2]
There is a built-in `AnimatedTexture` in FXGL, which can use multiple images as source and can also loop. Is it possible to use that, or does this custom implementation provide something new?

**Comment by marvinbuff** [comment]
Oh, I did not see that functionality of `AnimationChannel`. Thanks, I replaced it now. It works just fine. 
Maybe it could not hurt to have documentation on the various constructors, as I totally missed it. Especially, because the class emphasizes that it represents a channel from a sprite sheet.

Thank you for the tip.

**Comment by AlmasB** [comment]
Yes, the documentation is lagging a bit behind. I'll see what I can do once 11+ version has all of the 8 version's functionality restored.
