### ISSUE TITLE
BulletEffect

### ISSUE THREAD

**Issue by AlmasB** [marvinbuff/GalacticCombat#3]
I've only skimmed through the effect application, e.g. poison, slow, so not entirely sure, but this sounds like generic `Effect` class in FXGL, which is a temporary buff / behaviour to be applied to an entity via `EffectComponent`. For example:

```
   class PoisonEffect(duration: Duration) : Effect(duration) {
        override fun onStart(entity: Entity) {
            
        }

        override fun onUpdate(entity: Entity, tpf: Double) {
            
        }

        override fun onEnd(entity: Entity) {
            
        }
    }

...

entity.getComponent(EffectComponent::class.java).startEffect(effect)
```

Duration, duplicates (effect re-application) are automatically handled by EffectComponent. See if this can be refactored. If not, let me know what use case isn't covered, as I'd like to make the Effect API reasonably robust.

**Comment by marvinbuff** [comment]
Sorry for the delayed answer and thanks for the advise. 

I did not now of the `Effect` class, but upon inspection I don't think it is suited for me. 
The first problem is that the name of my effects are misleading as they also define the behaviour of the bullet itself. For instance the `BombEffect` will define that the bullet does not target an invader but actually a ground position and on impact it explodes, inflicting area damage. 
Second, the effects which can actually be considered effects, like the slow and poison, implement a different replacement strategy than is provided by your class. Small example: a poison effect has a set duration and damage per tick. If I apply a weak but long lasting poison, I don't want it be replaced by a shorter but stronger poison. Instead I want both poison effects to persist but only the strongest at a time should be considered to inflict damage. 
But this is just one option how to handle it and there are various combinations of strategies which I don't know if they can be combined into one Effect API. 

Does this make sense to you? Or am I missing something?

**Comment by AlmasB** [comment]
Hi,

This is good feedback. Not sure about 1, but 2 (replacement strategies)
sounds interesting. Each effect instance could provide a priority field
used to determine if it should replace an existing effect of same type.

A question arises from design perspective: can two effects of same type be
active at the same time with the priority applying the effect or does the
priority replace an existing effect. Let me know what you think,
particularly for general use case i.e. not just a single game

**Comment by marvinbuff** [comment]
Yes the first point is more why I won't use it in this particular case. 

I think having a general Effect class is quite hard to achieve. A complex but more or less general use case could look like this:

Positive and negative complementary effects like additional armour and vulnerability would force us to store each effect for the full duration. The final influence it has would be a combination of all persisting effects. E.g. 20% armour + 10% vulnerability(or -10% armour) would cancel out to 10%. However, on the first effect could persist for 20 seconds while the second one would only persists for 10 seconds.
What I want to show with this example is that a simple priority function might not be enough. I would suggest to change the EffectComponent to be opener to adjustements. I think it should be an open class with a generic type T, which defines what type of effects it handles. This way we can have different types stored more intuitively instead of using a list of types and group them logically together. It also makes it easier to get the current effects. For instance if we have a car which can have a speed buff, we might want to ask the EffectComponent<SpeedBuff> for the current modification and not just change the speed onStart and onEnd. 

I hope I expressed myself clear enough. Does this help?
